import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
DISTANCE_BEETWEEN_BUTTONS = 100

# Initial puck speed
INITIAL_PUCK_SPEED = 10

# Epsilon for collision (error margin)
EPSILON = 2

# Puck margins
TABLE_SIDE_WALLS = 55
TABLE_TOP_WALLS = 92
MARGINS = (TABLE_SIDE_WALLS, SCREEN_WIDTH - TABLE_SIDE_WALLS,	
		   TABLE_TOP_WALLS, SCREEN_HEIGHT - TABLE_TOP_WALLS)

# Gates dimensions for the map
GOAL_HEIGHT = 200
GOAL_TOP = (SCREEN_HEIGHT - GOAL_HEIGHT) // 2
GOAL_BOTTOM = GOAL_TOP + GOAL_HEIGHT

# Initial paddle speed
INITIAL_PADDLE_SPEED = 7

# Starting point for the paddles
DISTANCE_FROM_CENTER = 500

# Paddle margins
TABLE_SIDE_WALLS = 105
TABLE_TOP_WALLS = 140
PADDLE_CENTER_MARGIN = 57
MARGINS_ONE = (TABLE_SIDE_WALLS, SCREEN_WIDTH / 2 - PADDLE_CENTER_MARGIN,
               TABLE_TOP_WALLS, SCREEN_HEIGHT - TABLE_TOP_WALLS)
MARGINS_TWO = (SCREEN_WIDTH / 2 + PADDLE_CENTER_MARGIN, SCREEN_WIDTH - TABLE_SIDE_WALLS,
               TABLE_TOP_WALLS, SCREEN_HEIGHT - TABLE_TOP_WALLS)

pygame.init()
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))


__all__ = ['SCREEN_WIDTH', 'SCREEN_HEIGHT', 'GOAL_HEIGHT', 'GOAL_TOP', 'GOAL_BOTTOM',
           'DISTANCE_BEETWEEN_BUTTONS', 'INITIAL_PUCK_SPEED', 'TABLE_SIDE_WALLS', 'TABLE_TOP_WALLS',
           'MARGINS', 'SCREEN', 'INITIAL_PADDLE_SPEED', 'DISTANCE_FROM_CENTER', 'PADDLE_CENTER_MARGIN',
           'MARGINS_ONE', 'MARGINS_TWO', 'EPSILON']
