#TEXT_COLOR_NOT_TOUCHED = (207, 185, 11)

DISTANCE_BEETWEEN_BUTTONS = 100

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

__all__ = ['RectButton', 'DISTANCE_BEETWEEN_BUTTONS',
           'SCREEN_WIDTH', 'SCREEN_HEIGHT']