from .RectButton import RectButton


PRESS_START_2P = "utils/fonts/PressStart2P.ttf"
BUTTON_PATH = "utils/pictures/Button.png"
BACKGROUND_PATH = "utils/pictures/BackGround.jpeg"

#TEXT_COLOR_NOT_TOUCHED = (207, 185, 11)
TEXT_COLOR_NOT_TOUCHED = (223, 228, 139)
TEXT_COLOR_TOUCHED = (255, 0, 0)
TITLE_COLOR = (223, 228, 139)

DISTANCE_BEETWEEN_BUTTONS = 100

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

__all__ = ['RectButton', 'PRESS_START_2P', 'BUTTON_PATH',
           'BACKGROUND_PATH', 'TEXT_COLOR_NOT_TOUCHED',
           'TEXT_COLOR_TOUCHED', 'TITLE_COLOR', 'DISTANCE_BEETWEEN_BUTTONS',
           'SCREEN_WIDTH', 'SCREEN_HEIGHT']